[project]
name = "cryptax"
version = "0.1.0"
description = "Make tax auditors love crpyto."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "inquirer>=3.4.1",
    "polars>=1.35.2",
]
