[project]
name = "cryptax"
version = "0.3.0"
description = "Make tax auditors love crpyto."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "inquirer>=3.4.1",
    "numpy>=2.3.5",
    "polars>=1.35.2",
    "requests>=2.32.5",
    "xlsxwriter>=3.2.9",
]
